# site settings
title: Cumbria Eco Forum
email: contact@ecoforum.org.uk
description: Celebrating and Supporting Local Environmental Initiatives.
baseurl: # the subpath of your site, e.g. /blog
url:  https://ecoforum.org.uk # the base hostname & protocol for your site
author:
street_address: 37-39 Main Street
city: Sedbergh
state: Cumbria
zip_code: LA10 5BL
country: UK
phone: 01943 604030

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/Cumbria-Eco-Forum
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/CumbriaEco

# build settings
markdown: kramdown

sass:
  style: compressed

permalink: pretty
