---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: tiles
  label: Tiles
  create: all
  match: "**"
- type: directory
  path: awards
  label: Awards Pages
  create: all
  match: "**"
- type: directory
  path: awards/categories
  label: Award Categories
  create: documents
  match: "**"
  templates:
  - page
- type: directory
  path: forum
  label: Forum Pages
  create: documents
  match: "**"
- type: jekyll-posts
  label: Posts
  create: all
- type: document
  path: _data/team.yml
  label: Team
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
